name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
    #outputs:
    #myOutput:
    #description: 'Output to use'
    #default: 'none'
env:
  TAG:
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
